### ISSUE TITLE
battery cycle count not working in bigsur

### ISSUE THREAD

**Issue by mani2care** [palantir/jamf-pro-scripts#12]
battery cycle count not working in bigsur

**Comment by mpanighetti** [comment]
It appears to be working in Big Sur in my testing. Can you run `sh -x "/path/to/Battery Cycle Count.sh"` on one of your notebooks and show your output?

**Comment by mani2care** [comment]
sorry its from M1 chip with bigsur OS.

getting error by running the script :

"
{Ra03=0,Ra10=0,CellWom=(0,0),RaTableRaw=(<00000067005a0063006b0073005a005c00650068006b0067007900a700f20122>,<000000530048004f00590061004b004d00550058005c00580067009300df0119>,<00000067005a0063006c0074005c005e0067006a006e006a007b00ad01030143>),Qstart=0,AdapterPower=938726229,DailyMinSoc=59,Ra04=0,Ra11=0,CellVoltage=(3919,3919,3919),PackCurrentAccumulator=18446744073706264617,PassedCharge=12,Flags=16777217,PresentDOD=(41,41,41),Ra05=0,Ra12=0,FccComp1=5109,ChemID=9080,iMaxAndSocSmoothTable=<0000000000000000000000000000000000000000000000000000000000000000>,FccComp2=5109,PackCurrentAccumulatorCount=186059,DOD0=(6720,6720,6752),Ra06=0,ResScale=0,Ra13=0,WeightedRa=0,FilteredCurrent=0,RSS=0,CellCurrentAccumulatorCount=0,Serial=D861015ACKNL4D6EE,DailyMaxSoc=59,Ra07=0,Ra14=0,MaxCapacity=100,ChemicalWeightedRa=0,Ra00=0,BatteryHealthMetric=0,DesignCapacity=5103,Ra08=0,BatteryState=<000000000000000043e4000284000102>,CellCurrentAccumulator=(0,0),AlgoChemID=9080,MfgData=<0000000010020001237800000331353303303033035344490230000000000000>,ManufactureDate=54095955179570,ISS=0,Ra01=0,Soc1Voltage=0,QmaxDisqualificationReason=0,ChargeAccum=0,SimRate=0,Qmax=(5508,5492,5476),PMUConfigured=0,ITMiscStatus=0,StateOfCharge=59,Ra09=0,GaugeFlagRaw=192,CycleCount=3,Voltage=11756,SystemPower=1059216257,LifetimeData={Raw=<000000000000363300000000000000000031a32e0000e44712400000000000000191000911000db732ed296610f4f48f14bdf383f584f3e000af0000387a0001>,UpdateTime=1613038774,ResistanceUpdatedDisabledCount=0,TimeAtHighSoc=<00000000030000000000000000000000>,TemperatureSamples=14458,TotalOperatingTime=903,MaximumDischargeCurrent=18446744073709548687,MinimumPackVoltage=10598,MaximumPackVoltage=13037,MaximumChargeCurrent=4340,AverageTemperature=18446744073709551535,MinimumTemperature=9,RDISCnt=0,MaximumTemperature=401},Ra02=0}"

Thanks & Regards,

Manikandan R
Contact: +91-9902103878
E-mail: mani2care@gmail.com

**Comment by mani2care** [comment]
thanks now it's working.

without any issues.

Thanks & Regards,

Manikandan R
Contact: +91-9902103878
E-mail: mani2care@gmail.com
