### ISSUE TITLE
Reset Safari.sh does not clear last session

### ISSUE THREAD

**Issue by 4rm** [palantir/jamf-pro-scripts#43]
After running the Reset Safari script, the option to "Reopen All Windows from Last Session" persists, and successfully reopens tabs from the last session. This is on Safari 17.4, macOS 14.4. 

![image](https://github.com/palantir/jamf-pro-scripts/assets/3399474/d56d2232-b023-42b7-8ebf-6e0e0883dc6d)

**Comment by mpanighetti** [comment]
Thanks for the request! I found that deleting the contents of `~/Library/Containers/com.apple.Safari` clears the setting you called out. That change is in #44 (also took the opportunity to revamp the script using our uninstaller-template and added a few more container paths) and I've confirmed it works on my host, but it would be helpful to verify this satisfies your needs. Let me know!

**Comment by 4rm** [comment]
Thank you! I've tested the new script and it clears out the settings perfectly. This is resolved.
